# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'notification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "ThinkingSDK"

end

target 'random_app' do
  use_frameworks!
  pod "ThinkingSDK"
  pod 'FirebaseAnalytics'
  pod 'FirebaseMessaging'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
end
